# Generated by Django 3.1.3 on 2020-11-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
